# Generated by Django 4.2.4 on 2023-09-10 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_clientes_delete_autores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='nombre',
            new_name='nombre_cliente',
        ),
    ]
