# Generated by Django 4.2.4 on 2023-09-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_rename_nombre_clientes_nombre_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='nombre_cliente',
            new_name='nombre',
        ),
    ]
